/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.DeliveryPackage;
import Model.Product;
import Model.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author alilovepeach
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private DeliveryPackage delPackage;
    private Boolean validate = false;
    public CreateJPanel() {
        initComponents();
    }
    
    CreateJPanel(DeliveryPackage deliveryPackage){
        initComponents();
        this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageID = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productID = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 80, -1));
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, -1));
        add(productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 80, -1));
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, -1));
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, -1));

        customerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameFocusLost(evt);
            }
        });
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, -1));

        jLabel1.setText("Package ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 100, -1, -1));

        jLabel2.setText("Package Weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setText("product price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel4.setText("ProductID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setText("product name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel6.setText("Customer name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        customerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDActionPerformed(evt);
            }
        });
        add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 80, -1));

        jLabel7.setText("Customer ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        saveButton.setText("SAVE PRODUCT");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void customerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        String packID = packageID.getText();
        String packWeight = packageWt.getText();
//        String proID = productID.getText();
//        String proName = productName.getText();
//        String proPrice = productPrice.getText();
        String cusName = customerName.getText();
        String cusID = customerID.getText();
        
        this.delPackage.setPackageID(Integer.valueOf(packID));
        this.delPackage.setPackageWeight(Double.valueOf(packWeight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerID(Integer.valueOf(cusID));
        customer.setFullName(cusName);
        if(validate){
            JOptionPane.showMessageDialog(null, "please fill all field");

        }else{
            
        JOptionPane.showMessageDialog(null, "Saved");
        }
        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String proID = productID.getText();
        String proName = productName.getText();
        String proPrice = productPrice.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(proID), proName, Double.valueOf(proPrice));
//        product.setProductID(Integer.valueOf(proID));
//        product.setProductName(proName);
//        product.setPrice(Double.valueOf(proPrice));
        
        JOptionPane.showMessageDialog(null, "added product");
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void customerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFocusLost
        // TODO add your handling code here:
        System.out.println(customerName.getText() + " -- the customer name");
        String name = customerName.getText();
        
        if (name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill name");
            this.validate = true;
        }else{
            this.validate = false;
        }
    }//GEN-LAST:event_customerNameFocusLost
//
//    public boolean validateName(String name) {
//        String nameValidate = "[A-za-z]";
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField customerID;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageID;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
