/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author alilovepeach
 */
public class MedicineAssignmentJPanel extends javax.swing.JPanel {

    
    private Application application;
    /**
     * Creates new form MedicineAssignmentJPanel
     */
//    public MedicineAssignmentJPanel() {
//        initComponents();
//    }
    
    MedicineAssignmentJPanel(Application application){
        initComponents();
        
        this.application = application;
        populateDropDowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineBox = new javax.swing.JComboBox();
        observationBox = new javax.swing.JComboBox();
        assignMedBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineBoxActionPerformed(evt);
            }
        });
        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, -1));

        observationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                observationBoxItemStateChanged(evt);
            }
        });
        observationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observationBoxActionPerformed(evt);
            }
        });
        add(observationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 170, -1));

        assignMedBtn.setText("Assign");
        assignMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedBtnActionPerformed(evt);
            }
        });
        add(assignMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel1.setText("SHOW OBSERVATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel2.setText("observation");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel3.setText("medicine");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedBtnActionPerformed
        // TODO add your handling code here:
        
        // assign the selected medicine object to observation
        
        Observation o = (Observation) observationBox.getSelectedItem();
        
        Medicine m = (Medicine) medicineBox.getSelectedItem();
        o.setMedication(m);
    }//GEN-LAST:event_assignMedBtnActionPerformed

    private void observationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_observationBoxItemStateChanged
        // TODO add your handling code here:
        Observation o = (Observation) observationBox.getSelectedItem();
        
        if(o.getMedication() != null){
            jLabel1.setText(o.getMedication().getMedicineName());
        }
    }//GEN-LAST:event_observationBoxItemStateChanged

    private void observationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observationBoxActionPerformed

    private void medicineBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineBoxActionPerformed


    public void populateDropDowns(){
        
        ArrayList<Medicine> medicine = this.application.getCatalog().getMedicineList();
        
        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
        
        for(Observation o: observations) {
            observationBox.addItem(o);
        }
        for(Medicine med: medicine) {
            medicineBox.addItem(med);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox medicineBox;
    private javax.swing.JComboBox observationBox;
    // End of variables declaration//GEN-END:variables
}
