/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Customer.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alilovepeach
 */
public class CustomerManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerManagementJPanel
     */
    private Business business;
    private UserAccount userAccount;
    DefaultTableModel tableModel;
    
    public CustomerManagementJPanel(Business business, UserAccount userAccount) {
        initComponents();
        
        this.business = business;
        this.userAccount = userAccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldUsername1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        fieldName1 = new javax.swing.JTextField();
        fieldAge1 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsername1ActionPerformed(evt);
            }
        });
        jPanel1.add(fieldUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, -1));

        fieldPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassword1ActionPerformed(evt);
            }
        });
        jPanel1.add(fieldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, -1));
        jPanel1.add(fieldName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));
        jPanel1.add(fieldAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, -1));

        btnAdd.setText("Add Customer");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassword1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory uad = this.business.getUad();
        
        if(uad.accountExists(fieldUsername1.getText(), fieldPassword1.getText(), "customer")){
            JOptionPane.showMessageDialog(null, "sorry credential are taken");
        }else{
            UserAccount user = this.business.getUad().createUserAccount(fieldUsername1.getText(), fieldPassword1.getText(), "customer");
            this.business.getCd().createCustomer(user.getAccountId(), fieldName1.getText(), fieldAge1.getText());
            populate();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void fieldUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsername1ActionPerformed

    public void populate(){
        tableModel.setRowCount(0);
        for(Customer c: this.business.getCd().getCustomerList()){
            UserAccount u = this.business.getUad().findById(c.getPersonID());
            
            Object[] row = new Object[4];
            row[0] = c.getPersonID();
            row[1] = c.getName();
            row[2] = u.getUsername();
            row[3] = u.getPassword();
            
            tableModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField fieldAge1;
    private javax.swing.JTextField fieldName1;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldUsername1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
