/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Restaurant.DeliveryAgent;
import Services.Order;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alilovepeach
 */
public class OrderManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderManagementJPanel
     */
    private Business business;
    private UserAccount userAccount;
    DefaultTableModel tableModel;
    
    public OrderManagementJPanel(Business business, UserAccount userAccount) {
        initComponents();
        
        this.business = business;
        this.userAccount = userAccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populateDp();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        btnAssignAgent = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "OrderID", "Customer", "DeliveryMan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 200));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, 30));

        btnAssignAgent.setText("Assign");
        btnAssignAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignAgentActionPerformed(evt);
            }
        });
        add(btnAssignAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignAgentActionPerformed
        // TODO add your handling code here:
        DeliveryAgent agent = (DeliveryAgent) jComboBox1.getSelectedItem();
        
        int selectedRow = jTable1.getSelectedRow();
        
        Order o = (Order) jTable1.getValueAt(selectedRow, 0);
        o.setAgent(agent);
        agent.addDeliveryOrder(o);
        populate();
        
    }//GEN-LAST:event_btnAssignAgentActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void populate(){
        tableModel.setRowCount(0);
        for(Order o: this.business.getMol().getOrderList()){
 
            Object[] row = new Object[3];
            row[0] = o;
            row[1] = o.getCustomer().getPersonID();
            row[2] = o.getAgent().getPersonID();
            
            tableModel.addRow(row);
        }
    }
    
    public void populateDp(){
            jComboBox1.removeAllItems();
            for(DeliveryAgent d: this.business.getDad().getAgentList()){
                jComboBox1.addItem(d);
            }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignAgent;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
